[phases.setup]
nixPkgs = ['python311', 'pip']
nixLibs = ['zlib', 'openssl']

[phases.build]
cmds = [
    'cd backend',
    'pip install -r requirements.txt'
]

[phases.start]
cmd = 'cd backend && python -m gunicorn -c ../gunicorn.conf.py app.main:app'

[variables]
PIP_CACHE_DIR = "/tmp/pip-cache"
PYTHONPATH = "/app/backend"