"""Add scheduler support to TaskLog and UserPreference models

Revision ID: 52672a06947a
Revises: 58305ba6e357
Create Date: 2025-07-14 11:57:44.511130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52672a06947a'
down_revision: Union[str, None] = '58305ba6e357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_logs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_logs', sa.Column('scheduler_job_id', sa.String(length=255), nullable=True))
    op.add_column('task_logs', sa.Column('task_unique_key', sa.String(length=255), nullable=True))
    op.add_column('task_logs', sa.Column('execution_node', sa.String(length=100), nullable=True))
    op.create_index('idx_task_logs_scheduler_job_id', 'task_logs', ['scheduler_job_id'], unique=False)
    op.create_index('idx_task_logs_unique_key', 'task_logs', ['task_unique_key'], unique=False)
    op.add_column('user_preferences', sa.Column('daily_report_time', sa.Time(), nullable=True))
    op.add_column('user_preferences', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'auto_sync_enabled')
    op.drop_column('user_preferences', 'timezone')
    op.drop_column('user_preferences', 'daily_report_time')
    op.drop_index('idx_task_logs_unique_key', table_name='task_logs')
    op.drop_index('idx_task_logs_scheduler_job_id', table_name='task_logs')
    op.drop_column('task_logs', 'execution_node')
    op.drop_column('task_logs', 'task_unique_key')
    op.drop_column('task_logs', 'scheduler_job_id')
    op.drop_column('task_logs', 'next_retry_at')
    # ### end Alembic commands ###
