"""add oauth_sessions table

Revision ID: bb2c76bce297
Revises: 11d05b7e2a0c
Create Date: 2025-07-16 14:05:15.620837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2c76bce297'
down_revision: Union[str, None] = '11d05b7e2a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create oauth_sessions table
    op.create_table('oauth_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', 'CONSUMED', name='oauthsessionstatus'), nullable=False),
        sa.Column('flow_data', sa.Text(), nullable=False),
        sa.Column('authorization_url', sa.Text(), nullable=False),
        sa.Column('state', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_sessions_id'), 'oauth_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_sessions_session_id'), 'oauth_sessions', ['session_id'], unique=True)
    
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    
    # Drop oauth_sessions table
    op.drop_index(op.f('ix_oauth_sessions_session_id'), table_name='oauth_sessions')
    op.drop_index(op.f('ix_oauth_sessions_id'), table_name='oauth_sessions')
    op.drop_table('oauth_sessions')
    
    # Drop enum type
    op.execute('DROP TYPE IF EXISTS oauthsessionstatus')
    # ### end Alembic commands ###
