"""Add UserSyncStatus table for email sync tracking

Revision ID: f00564e3c768
Revises: aa44f75eab15
Create Date: 2025-07-21 18:53:45.311220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f00564e3c768'
down_revision: Union[str, None] = 'aa44f75eab15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sync_status',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_syncing', sa.Boolean(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('current_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sync_status')
    # ### end Alembic commands ###
