"""increase avatar_url field length

Revision ID: f01f87d404d5
Revises: 52672a06947a
Create Date: 2025-07-16 13:47:25.599277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f01f87d404d5'
down_revision: Union[str, None] = '52672a06947a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    
    # Increase avatar_url field length from 500 to 1000
    op.alter_column('users', 'avatar_url',
                    existing_type=sa.VARCHAR(length=500),
                    type_=sa.VARCHAR(length=1000),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert avatar_url field length back to 500
    op.alter_column('users', 'avatar_url',
                    existing_type=sa.VARCHAR(length=1000),
                    type_=sa.VARCHAR(length=500),
                    existing_nullable=True)
    
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
